name: tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Run tests
        run: wasm-pack test --chrome --headless
